language: php

php:
  - 5.6

env:
  CODECLIMATE_REPO_TOKEN: bdb7f2e80cc1164be069fa442eba4f6ef8b02cafbcfa39d13420e3120a5163ba

addons:
  code_climate:
    repo_token: bdb7f2e80cc1164be069fa442eba4f6ef8b02cafbcfa39d13420e3120a5163ba

install:
  - composer install

after_script:
  - vendor/bin/test-reporter
